services:
  - type: web
    name: youtubeurl-to-streamurl
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
    healthCheckPath: /
