services:
  - type: web
    name: youtubeurl-to-streamurl
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node my-invidious-tool/src/index.js # 正しいパスを指定
    rootDir: my-invidious-tool      # プロジェクトのルートディレクトリ
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
    healthCheckPath: /
